module.exports = {
  text: {
    primary: 'hsl(var(--color-text-primary) / <alpha-value>)',
    secondary: 'hsl(var(--color-text-secondary) / <alpha-value>)',
    tertiary: 'hsl(var(--color-text-tertiary) / <alpha-value>)',
    disable: 'hsl(var(--color-text-disable) / <alpha-value>)',
    white: 'hsl(var(--color-text-white) / <alpha-value>)',
  },
  background: {
    DEFAULT: 'hsl(var(--background))',
    bottom: 'hsl(var(--color-background-bottom) / <alpha-value>)',
    'bottom-secondary':
      'hsl(var(--color-background-bottom-secondary) / <alpha-value>)',
    white: 'hsl(var(--color-background-white) / <alpha-value>)',
    top: 'hsl(var(--color-background-top) / <alpha-value>)',
    'top-active': 'hsl(var(--color-background-top-active) / <alpha-value>)',
    border: 'hsl(var(--color-background-border) / <alpha-value>)',
  },
  brand: {
    50: 'hsl(var(--color-brand-50) / <alpha-value>)',
    100: 'hsl(var(--color-brand-100) / <alpha-value>)',
    200: 'hsl(var(--color-brand-200) / <alpha-value>)',
    300: 'hsl(var(--color-brand-300) / <alpha-value>)',
    400: 'hsl(var(--color-brand-400) / <alpha-value>)',
    500: 'hsl(var(--color-brand-500) / <alpha-value>)',
    600: 'hsl(var(--color-brand-600) / <alpha-value>)',
    700: 'hsl(var(--color-brand-700) / <alpha-value>)',
    800: 'hsl(var(--color-brand-800) / <alpha-value>)',
    900: 'hsl(var(--color-brand-900) / <alpha-value>)',
  },
  gray: {
    50: 'hsl(var(--color-gray-50) / <alpha-value>)',
    100: 'hsl(var(--color-gray-100) / <alpha-value>)',
    200: 'hsl(var(--color-gray-200) / <alpha-value>)',
    300: 'hsl(var(--color-gray-300) / <alpha-value>)',
    400: 'hsl(var(--color-gray-400) / <alpha-value>)',
    500: 'hsl(var(--color-gray-500) / <alpha-value>)',
    600: 'hsl(var(--color-gray-600) / <alpha-value>)',
    700: 'hsl(var(--color-gray-700) / <alpha-value>)',
    800: 'hsl(var(--color-gray-800) / <alpha-value>)',
    900: 'hsl(var(--color-gray-900) / <alpha-value>)',
  },
  status: {
    50: 'hsl(var(--color-status-50) / <alpha-value>)',
    100: 'hsl(var(--color-status-100) / <alpha-value>)',
    200: 'hsl(var(--color-status-200) / <alpha-value>)',
    300: 'hsl(var(--color-status-300) / <alpha-value>)',
    400: 'hsl(var(--color-status-400) / <alpha-value>)',
    500: 'hsl(var(--color-status-500) / <alpha-value>)',
    600: 'hsl(var(--color-status-600) / <alpha-value>)',
    700: 'hsl(var(--color-status-700) / <alpha-value>)',
  },
  blue: {
    default: 'hsl(var(--color-blue-default) / <alpha-value>)',
    active: 'hsl(var(--color-blue-active) / <alpha-value>)',
  },
  pink: {
    default: 'hsl(var(--color-pink-default) / <alpha-value>)',
    active: 'hsl(var(--color-pink-active) / <alpha-value>)',
  },
  jade: {
    default: 'hsl(var(--color-jade-default) / <alpha-value>)',
    active: 'hsl(var(--color-jade-active) / <alpha-value>)',
  },
  lime: {
    default: 'hsl(var(--color-lime-default) / <alpha-value>)',
    active: 'hsl(var(--color-lime-active) / <alpha-value>)',
  },
  orange: {
    default: 'hsl(var(--color-orange-default) / <alpha-value>)',
    active: 'hsl(var(--color-orange-active) / <alpha-value>)',
  },
  purple: {
    default: 'hsl(var(--color-purple-default) / <alpha-value>)',
    active: 'hsl(var(--color-purple-active) / <alpha-value>)',
  },
  light: 'hsl(var(--color-light) / <alpha-value>)',
  dark: 'hsl(var(--color-dark) / <alpha-value>)',
  avatar: {
    background: 'hsl(var(--color-avatar-background) / <alpha-value>)',
    border: 'hsl(var(--color-avatar-border) / <alpha-value>)',
    overlay: 'hsl(var(--color-avatar-overlay) / <alpha-value>)',
  },
};
