import { writeFileSync } from 'fs';

import { colorValues } from '../src/design/tokens/colorValues';

export interface ColorToken {
  value: string;
  comment?: string;
}

export const banner = `/*
 * This file is automatically generated by \`pnpm generate:tokens\`.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Update \`src/design/tokens/colorValues.ts\` instead.
 */

@layer base {
  :root {
`;

export const footer = `  }
}
`;

export function generateCssString(tokens: Record<string, ColorToken>): string {
  let content = banner;

  for (const [key, token] of Object.entries(tokens)) {
    const commentPart = token.comment ? ` /* ${token.comment} */` : '';
    content += `    --${key}: ${token.value};${commentPart}\n`;
  }

  content += footer;
  return content;
}

export function generateTokens() {
  const content = generateCssString(colorValues);
  const outputPath = 'src/styles/colors.css';
  writeFileSync(outputPath, content, 'utf-8');
  console.log(`Successfully generated CSS custom properties to ${outputPath}`);
}

if (!process.env.VITEST) {
  generateTokens();
}
