import { writeFileSync } from 'fs';

import { colorValues } from '../src/design/tokens/colorValues.ts';

const banner = `/*
 * This file is automatically generated by \`pnpm generate:tokens\`.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Update \`src/design/tokens/colorValues.ts\` instead.
 */

@layer base {
  :root {
`;

const footer = `  }
}
`;

function generateTokens() {
  let content = banner;

  for (const [key, token] of Object.entries(colorValues)) {
    const commentPart = token.comment ? ` /* ${token.comment} */` : '';
    content += `    --${key}: ${token.value};${commentPart}\n`;
  }

  content += footer;

  const outputPath = 'src/styles/colors.css';
  writeFileSync(outputPath, content, 'utf-8');
  console.log(`Successfully generated CSS custom properties to ${outputPath}`);
}

generateTokens();
