import fs from 'fs';
import path from 'path';

const TS_SOURCE_PATH = path.resolve('src/design/tokens/color-values.ts');
const CSS_OUTPUT_PATH = path.resolve('src/styles/tokens.css');

export function normalizeCSS(str) {
  return str.replace(/\r\n/g, '\n').trim();
}

export function parseTSContent(tsContent) {
  const lines = tsContent.split(/\r?\n/);
  const cssLines = [
    '/* This file is automatically generated from src/design/tokens/color-values.ts. Do not edit directly. */',
    ':root {',
  ];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();
    if (!trimmed) {
      continue;
    }

    // Match key-value pair, e.g., "text-primary": "225 12% 13%", // #1E2026
    const kvMatch = trimmed.match(
      /^["']?([a-zA-Z0-9-]+)["']?\s*:\s*["']([^"']+)["']\s*,?\s*(?:\/\/\s*(.*))?$/
    );
    if (kvMatch) {
      const [, key, value, comment] = kvMatch;
      const commentStr = comment ? ` /* ${comment.trim()} */` : '';
      cssLines.push(`  --color-${key}: ${value};${commentStr}`);
      continue;
    }

    // Match section headers or other comments
    const commentMatch = trimmed.match(/^\/\/\s*(.*)$/);
    if (commentMatch) {
      const content = commentMatch[1].trim();
      // Ignore initial file-level comments or type imports
      if (
        content &&
        !content.startsWith('This file') &&
        !content.startsWith('Regenerate')
      ) {
        cssLines.push(`  /* ${content} */`);
      }
      continue;
    }

    // Check if the line is a structural line that should be safely ignored
    const isStructural =
      trimmed.startsWith('export const') ||
      trimmed.startsWith('export type') ||
      trimmed.startsWith('} as const;') ||
      trimmed.startsWith('/**') ||
      trimmed.startsWith('*') ||
      trimmed.startsWith('*/') ||
      trimmed.startsWith('import');

    if (!isStructural) {
      throw new Error(
        `Line ${i + 1} is malformed or invalid color token syntax: "${line}"`
      );
    }
  }

  cssLines.push('}');
  return cssLines.join('\n') + '\n';
}

export function generateCSS() {
  if (!fs.existsSync(TS_SOURCE_PATH)) {
    console.error(`Error: TS source file not found at ${TS_SOURCE_PATH}`);
    process.exit(1);
  }

  const tsContent = fs.readFileSync(TS_SOURCE_PATH, 'utf8');
  try {
    return parseTSContent(tsContent);
  } catch (error) {
    console.error(
      '========================================================================'
    );
    console.error(`Error: Failed to compile design tokens.`);
    console.error(error.message);
    console.error(
      '========================================================================'
    );
    process.exit(1);
  }
}

function main() {
  const isCheckMode = process.argv.includes('--check');
  const generatedCSS = generateCSS();

  if (isCheckMode) {
    if (!fs.existsSync(CSS_OUTPUT_PATH)) {
      console.error(
        `Error: Generated CSS file not found at ${CSS_OUTPUT_PATH}`
      );
      console.error(
        "Please run 'pnpm generate:tokens' locally and commit the result."
      );
      process.exit(1);
    }

    const existingCSS = fs.readFileSync(CSS_OUTPUT_PATH, 'utf8');

    if (normalizeCSS(existingCSS) !== normalizeCSS(generatedCSS)) {
      console.error(
        '========================================================================'
      );
      console.error('Error: Design token CSS drift detected.');
      console.error(`The committed CSS file '${CSS_OUTPUT_PATH}'`);
      console.error(
        `does not match the latest source 'src/design/tokens/color-values.ts'.`
      );
      console.error(
        "Please run 'pnpm generate:tokens' locally and commit the result."
      );
      console.error(
        '========================================================================'
      );
      process.exit(1);
    }

    console.log('Design tokens check passed. No drift detected.');
    process.exit(0);
  } else {
    fs.writeFileSync(CSS_OUTPUT_PATH, generatedCSS, 'utf8');
    console.log(`Successfully generated CSS tokens at ${CSS_OUTPUT_PATH}`);
    process.exit(0);
  }
}

if (typeof process !== 'undefined' && !process.env.VITEST) {
  main();
}
