import { describe, expect, it } from 'vitest';
import {
  generateCSS,
  normalizeCSS,
  parseTSContent,
} from './generate-tokens.mjs';

describe('Design Token Generator - Helpers', () => {
  describe('normalizeCSS()', () => {
    it('should normalize CRLF (Windows) and LF (Linux) newlines for deterministic checks', () => {
      const crlfContent = ':root {\r\n  --color-brand: 180 50% 50%;\r\n}\r\n';
      const lfContent = ':root {\n  --color-brand: 180 50% 50%;\n}\n';

      expect(normalizeCSS(crlfContent)).toBe(normalizeCSS(lfContent));
      expect(normalizeCSS(crlfContent)).toBe(
        ':root {\n  --color-brand: 180 50% 50%;\n}'
      );
    });
  });

  describe('parseTSContent() - Edge Cases & Robustness', () => {
    it('should parse single quotes, double quotes, varying indentation, and comment structures', () => {
      const tsMock = `
        export const rawColors = {
          // Color System
          "text-primary": "225 12% 13%", // #1E2026
          'text-secondary': '218 10% 31%', // #474D57
          brand-500 : "180 64% 48%" ,
          "gray-100": "0 0% 91%",//#E9E9E9
          // Section Ending
        } as const;
      `;

      const result = parseTSContent(tsMock);

      expect(result).toContain('/* Color System */');
      expect(result).toContain(
        '--color-text-primary: 225 12% 13%; /* #1E2026 */'
      );
      expect(result).toContain(
        '--color-text-secondary: 218 10% 31%; /* #474D57 */'
      );
      expect(result).toContain('--color-brand-500: 180 64% 48%;');
      expect(result).toContain('--color-gray-100: 0 0% 91%; /* #E9E9E9 */');
      expect(result).toContain('/* Section Ending */');
    });

    it('should correctly ignore valid structural TS lines', () => {
      const tsMock = `
        import { something } from 'somewhere';
        /**
         * Documentation comment block
         * with multiple lines
         */
        export const rawColors = {
          "text-primary": "225 12% 13%",
        } as const;
        export type RawColorKey = keyof typeof rawColors;
      `;

      expect(() => parseTSContent(tsMock)).not.toThrow();
      const result = parseTSContent(tsMock);
      expect(result).toContain('--color-text-primary: 225 12% 13%;');
    });

    it('should throw an error on malformed tokens using underscores or invalid characters', () => {
      const tsMock = `
        export const rawColors = {
          "text_primary": "225 12% 13%",
        } as const;
      `;

      expect(() => parseTSContent(tsMock)).toThrowError(
        /Line 3 is malformed or invalid color token syntax/
      );
    });

    it('should throw an error on missing quotes for value definitions', () => {
      const tsMock = `
        export const rawColors = {
          "text-primary": 225 12% 13%,
        } as const;
      `;

      expect(() => parseTSContent(tsMock)).toThrowError(
        /Line 3 is malformed or invalid color token syntax/
      );
    });

    it('should throw an error on totally invalid code/syntax inside the file', () => {
      const tsMock = `
        const someOtherVariable = "hello world";
      `;

      expect(() => parseTSContent(tsMock)).toThrowError(
        /Line 2 is malformed or invalid color token syntax/
      );
    });
  });
});

describe('Design Token Generator - Integration', () => {
  it('should successfully compile the actual TS source colors into CSS custom properties', () => {
    const cssResult = generateCSS();

    expect(cssResult).toContain('This file is automatically generated');
    expect(cssResult).toContain(':root {');
    expect(cssResult).toContain(
      '--color-text-primary: 225 12% 13%; /* #1E2026 */'
    );
    expect(cssResult).toContain(
      '--color-text-secondary: 218 10% 31%; /* #474D57 */'
    );
    expect(cssResult).toContain(
      '--color-brand-500: 180 64% 48%; /* #2CCBCB */'
    );
    expect(cssResult).toContain(
      '--color-status-success-default: 137 100% 36%; /* #00BA34 */'
    );
    expect(cssResult).toContain('/* Color System Tokens */');
    expect(cssResult).toContain('/* Legacy / Landing page specific colors */');
    expect(cssResult.trim().endsWith('}')).toBe(true);
    expect(cssResult.endsWith('\n')).toBe(true);
  });
});
