name: Unit & Integration Tests

on:
  pull_request:
    branches: ['**']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit & Integration Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up environment
        uses: ./.github/actions/setup-env

      - name: Run unit & integration tests
        run: pnpm test
